Fixes to upload Release

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -38,7 +38,7 @@ jobs:
         cmake -B build -S . \
           -DCMAKE_TOOLCHAIN_FILE=$GITHUB_WORKSPACE/vcpkg/scripts/buildsystems/vcpkg.cmake \
           -DWITH_GOOGLE_TEST=ON
-
+          -DPATCH_VERSION=${{ github.run_number }}
     - name: Build Release
       run: |
         cmake --build build --config Release
@@ -75,3 +75,34 @@ jobs:
           build/*.deb
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+    
+    - name: Find .deb file
+      id: find_deb
+      run: |
+        DEB_FILE=$(find build -name "bayan-0.0.*-Linux.deb" | head -n 1)
+        if [[ -z "${DEB_FILE}" ]]; then
+          echo "Error: .deb file not found!"
+          exit 1
+        fi
+        echo "DEB_FILE=${DEB_FILE}" | tee output.txt
+        echo "DEB_FILE=${DEB_FILE}" >> $GITHUB_OUTPUT
+    - name: Create Release
+      id: create_release
+      uses: actions/create-release@v1
+      env:
+        GITHUB_TOKEN: ${{ secrets.PAT }}
+      with:
+        tag_name: ${{ github.run_number }}
+        release_name: Release ${{ github.run_number }}
+        draft: false
+        prerelease: false
+      - name: Upload Release Asset
+        id: upload-release-asset
+        uses: actions/upload-release-asset@v1
+        env:
+          GITHUB_TOKEN: ${{ secrets.PAT }}
+        with:
+          upload_url: ${{ steps.create_release.outputs.upload_url }}
+          asset_path: ${{ steps.find_deb.outputs.DEB_FILE }}
+          asset_name: bulk-0.0.${{ github.run_number }}-Linux.deb
+          asset_content_type: application/vnd.debian.binary-package
